/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - OutputsSubject
 * - OutputsVariableSubject
 * - OutputsContractCreatedSubject
 * - OutputsCoinSubject
 * - OutputsChangeSubject
 * - OutputsContractSubject
 */

import { OutputParser } from '../../parsers';
import type {
  Address,
  AssetId,
  BlockHeight,
  ContractId,
  Output,
  OutputType,
  RawOutput,
  TxId,
} from '../../types';
import { SubjectBase } from '../subject-base';

type OutputsFields = {
  outputType: OutputType;
  outputIndex: number;
  txId: TxId;
  txIndex: number;
  blockHeight: BlockHeight;
};

export class OutputsSubject extends SubjectBase<
  OutputsFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs',
    format:
      'outputs.{output_type}.{block_height}.{tx_id}.{tx_index}.{output_index}',
    parser: new OutputParser(),
  };
}

type OutputsVariableFields = {
  blockHeight: BlockHeight;
  asset: AssetId;
  txId: TxId;
  txIndex: number;
  to: Address;
  outputIndex: number;
};

export class OutputsVariableSubject extends SubjectBase<
  OutputsVariableFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs_variable',
    format:
      'outputs.variable.{block_height}.{tx_id}.{tx_index}.{output_index}.{to}.{asset}',
    parser: new OutputParser(),
  };
}

type OutputsContractCreatedFields = {
  txIndex: number;
  outputIndex: number;
  blockHeight: BlockHeight;
  contract: ContractId;
  txId: TxId;
};

export class OutputsContractCreatedSubject extends SubjectBase<
  OutputsContractCreatedFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs_contract_created',
    format:
      'outputs.contract_created.{block_height}.{tx_id}.{tx_index}.{output_index}.{contract}',
    parser: new OutputParser(),
  };
}

type OutputsCoinFields = {
  outputIndex: number;
  to: Address;
  txIndex: number;
  blockHeight: BlockHeight;
  asset: AssetId;
  txId: TxId;
};

export class OutputsCoinSubject extends SubjectBase<
  OutputsCoinFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs_coin',
    format:
      'outputs.coin.{block_height}.{tx_id}.{tx_index}.{output_index}.{to}.{asset}',
    parser: new OutputParser(),
  };
}

type OutputsChangeFields = {
  outputIndex: number;
  asset: AssetId;
  txId: TxId;
  blockHeight: BlockHeight;
  to: Address;
  txIndex: number;
};

export class OutputsChangeSubject extends SubjectBase<
  OutputsChangeFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs_change',
    format:
      'outputs.change.{block_height}.{tx_id}.{tx_index}.{output_index}.{to}.{asset}',
    parser: new OutputParser(),
  };
}

type OutputsContractFields = {
  txIndex: number;
  blockHeight: BlockHeight;
  contract: ContractId;
  txId: TxId;
  outputIndex: number;
};

export class OutputsContractSubject extends SubjectBase<
  OutputsContractFields,
  Output,
  RawOutput
> {
  metadata = {
    id: 'outputs_contract',
    format:
      'outputs.contract.{block_height}.{tx_id}.{tx_index}.{output_index}.{contract}',
    parser: new OutputParser(),
  };
}
