/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - TransactionsByIdSubject
 * - TransactionsSubject
 */

import type {
  BlockHeight,
  Bytes32,
  IdentifierKind,
  TransactionKind,
  TransactionStatus,
} from '../../types';
import { SubjectBase } from '../subject-base';
type TransactionsFields = {
  blockHeight: BlockHeight;
  index: number;
  txId: Bytes32;
  status: TransactionStatus;
  kind: TransactionKind;
};

export class TransactionsSubject extends SubjectBase<TransactionsFields> {
  protected format =
    'transactions.{block_height}.{index}.{tx_id}.{status}.{kind}';
}

type TransactionsByIdFields = {
  txId: Bytes32;
  index: number;
  idKind: IdentifierKind;
  idValue: Bytes32;
};

export class TransactionsByIdSubject extends SubjectBase<TransactionsByIdFields> {
  protected format = 'by_id.transactions.{tx_id}.{index}.{id_kind}.{id_value}';
}
