/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 */

import type {
  BN,
  BytesLike,
  Block as FuelsBlock,
  Input as FuelsInput,
  InputCoin as FuelsInputCoin,
  InputContract as FuelsInputContract,
  InputMessage as FuelsInputMessage,
  Output as FuelsOutput,
  OutputChange as FuelsOutputChange,
  OutputCoin as FuelsOutputCoin,
  OutputContract as FuelsOutputContract,
  OutputContractCreated as FuelsOutputContractCreated,
  OutputVariable as FuelsOutputVariable,
  Receipt as FuelsReceipt,
  Transaction as FuelsTransaction,
  TransactionType,
} from 'fuels';

// ----------------------------------------------------------------------------
// Base Types
// ----------------------------------------------------------------------------
export type Bytes32 = BytesLike;
export type Address = string;
export type AssetId = string;
export type ContractId = string;
export type BlockHeight = number;
export type MessageId = string;
export type TxId = string;
export type HexData = string;

export type UtxoId = {
  txId: string;
  outputIndex: number;
};

export type TxPointer = {
  blockHeight: number;
  txIndex: number;
};

// ----------------------------------------------------------------------------
// Stream Types
// ----------------------------------------------------------------------------
export enum StreamNames {
  Blocks = 'blocks',
  Inputs = 'inputs',
  Outputs = 'outputs',
  Receipts = 'receipts',
  Transactions = 'transactions',
  Utxos = 'utxos',
}

export enum ClientStatus {
  Connected = 'connected',
  Disconnected = 'disconnected',
  Reconnecting = 'reconnecting',
  Disconnecting = 'disconnecting',
  Errored = 'errored',
  Stale = 'stale',
}

// ----------------------------------------------------------------------------
// Identifier Types
// ----------------------------------------------------------------------------
export enum IdentifierKind {
  AssetID = 'asset_id',
  ContractID = 'contract_id',
}

// ----------------------------------------------------------------------------
// Block Types
// ----------------------------------------------------------------------------
export type RawBlock = {
  id: string;
  height: number;
  time: string;
  transactionIds: string[];
  version: 'V1';
  consensus: {
    type: 'Genesis' | 'PoAConsensus';
    signature?: string;
    chainConfigHash?: string;
    coinsRoot?: string;
    contractsRoot?: string;
    messagesRoot?: string;
    transactionsRoot?: string;
  };
  header: {
    daHeight: number;
    stateTransitionBytecodeVersion: number;
    transactionsCount: number;
    transactionsRoot: string;
    messageOutboxRoot: string;
    eventInboxRoot: string;
    prevRoot: string;
    applicationHash: string;
    consensusParametersVersion: number;
    height: number;
    messageReceiptCount: number;
    time: string;
    version: 'V1';
    id: string;
  };
};

export type Block = FuelsBlock & {
  consensus: RawBlock['consensus'];
  version: RawBlock['version'];
};

// ----------------------------------------------------------------------------
// Output Types
// ----------------------------------------------------------------------------
export enum OutputType {
  Coin = 'Coin',
  Contract = 'Contract',
  Change = 'Change',
  Variable = 'Variable',
  ContractCreated = 'ContractCreated',
}

export type RawCoinOutput = {
  type: OutputType.Coin;
  amount: number;
  assetId: string;
  to: string;
};

export type RawContractOutput = {
  type: OutputType.Contract;
  balanceRoot: string;
  stateRoot: string;
  inputIndex: number;
};

export type RawChangeOutput = {
  type: OutputType.Change;
  amount: number;
  assetId: string;
  to: string;
};

export type RawVariableOutput = {
  type: OutputType.Variable;
  amount: number;
  assetId: string;
  to: string;
};

export type RawContractCreated = {
  type: OutputType.ContractCreated;
  contractId: string;
  stateRoot: string;
};

export type RawOutput =
  | RawCoinOutput
  | RawContractOutput
  | RawChangeOutput
  | RawVariableOutput
  | RawContractCreated;

export type OutputCoin = FuelsOutputCoin;
export type OutputContract = FuelsOutputContract;
export type OutputChange = FuelsOutputChange;
export type OutputVariable = FuelsOutputVariable;
export type OutputContractCreated = FuelsOutputContractCreated;
export type Output = FuelsOutput;

// ----------------------------------------------------------------------------
// Input Types
// ----------------------------------------------------------------------------
export enum InputType {
  Coin = 'Coin',
  Contract = 'Contract',
  Message = 'Message',
}

export type RawInputCoin = {
  type: InputType.Coin;
  amount: number;
  assetId: string;
  owner: string;
  predicate: string;
  predicateData: string;
  predicateGasUsed: number;
  predicateDataLength: number;
  predicateLength: number;
  txPointer: TxPointer;
  utxoId: UtxoId;
  witnessIndex: number;
};

export type RawInputContract = {
  type: InputType.Contract;
  balanceRoot: string;
  stateRoot: string;
  txPointer: TxPointer;
  utxoId: UtxoId;
  contractId: string;
};

export type RawInputMessage = {
  type: InputType.Message;
  amount: number;
  data?: string;
  nonce: string;
  predicate: string;
  predicateData: string;
  predicateGasUsed: number;
  predicateDataLength: number;
  predicateLength: number;
  recipient: string;
  sender: string;
  witnessIndex: number;
};

export type RawInput = RawInputCoin | RawInputContract | RawInputMessage;
export type InputCoin = FuelsInputCoin;
export type InputContract = FuelsInputContract;
export type InputMessage = FuelsInputMessage;
export type Input = FuelsInput;

// ----------------------------------------------------------------------------
// Receipt Types
// ----------------------------------------------------------------------------
export enum ReceiptType {
  Call = 'Call',
  Return = 'Return',
  ReturnData = 'ReturnData',
  Panic = 'Panic',
  Revert = 'Revert',
  Log = 'Log',
  LogData = 'LogData',
  Transfer = 'Transfer',
  TransferOut = 'TransferOut',
  ScriptResult = 'ScriptResult',
  MessageOut = 'MessageOut',
  Mint = 'Mint',
  Burn = 'Burn',
}

export type RawCallReceipt = {
  type: ReceiptType.Call;
  id: string;
  to: string;
  amount: number;
  assetId: string;
  gas: number;
  param1: number;
  param2: number;
  pc: number;
  is: number;
};

export type RawReturnReceipt = {
  type: ReceiptType.Return;
  id: string;
  val: number;
  pc: number;
  is: number;
};

export type RawReturnDataReceipt = {
  type: ReceiptType.ReturnData;
  id: string;
  ptr: number;
  len: number;
  digest: string;
  pc: number;
  is: number;
  data?: string;
};

export type RawPanicReceipt = {
  type: ReceiptType.Panic;
  id: string;
  reason: number;
  pc: number;
  is: number;
  contractId?: string;
};

export type RawRevertReceipt = {
  type: ReceiptType.Revert;
  id: string;
  ra: number;
  pc: number;
  is: number;
};

export type RawLogReceipt = {
  type: ReceiptType.Log;
  id: string;
  ra: number;
  rb: number;
  rc: number;
  rd: number;
  pc: number;
  is: number;
};

export type RawLogDataReceipt = {
  type: ReceiptType.LogData;
  id: string;
  ra: number;
  rb: number;
  ptr: number;
  len: number;
  digest: string;
  pc: number;
  is: number;
  data?: string;
};

export type RawTransferReceipt = {
  type: ReceiptType.Transfer;
  id: string;
  to: string;
  amount: number;
  assetId: string;
  pc: number;
  is: number;
};

export type RawTransferOutReceipt = {
  type: ReceiptType.TransferOut;
  id: string;
  to: string;
  amount: number;
  assetId: string;
  pc: number;
  is: number;
};

export type RawScriptResultReceipt = {
  type: ReceiptType.ScriptResult;
  result: number;
  gasUsed: number;
};

export type RawMessageOutReceipt = {
  type: ReceiptType.MessageOut;
  sender: string;
  recipient: string;
  amount: number;
  nonce: string;
  len: number;
  digest: string;
  data?: string;
};

export type RawMintReceipt = {
  type: ReceiptType.Mint;
  subId: string;
  contractId: string;
  val: number;
  pc: number;
  is: number;
};

export type RawBurnReceipt = {
  type: ReceiptType.Burn;
  subId: string;
  contractId: string;
  val: number;
  pc: number;
  is: number;
};

export type RawReceipt =
  | RawCallReceipt
  | RawReturnReceipt
  | RawReturnDataReceipt
  | RawPanicReceipt
  | RawRevertReceipt
  | RawLogReceipt
  | RawLogDataReceipt
  | RawTransferReceipt
  | RawTransferOutReceipt
  | RawScriptResultReceipt
  | RawMessageOutReceipt
  | RawMintReceipt
  | RawBurnReceipt;

export type Receipt = FuelsReceipt;

// ----------------------------------------------------------------------------
// UTXO Types
// ----------------------------------------------------------------------------
export type RawUtxo = {
  utxoId: UtxoId;
  sender?: string;
  recipient?: string;
  nonce?: string;
  data?: string;
  amount?: number;
  txId: string;
};

export type Utxo = {
  utxoId: UtxoId;
  sender?: string;
  recipient?: string;
  nonce?: string;
  data?: string;
  amount?: BN;
  txId: string;
};

export enum UtxoType {
  Contract = 'Contract',
  Coin = 'Coin',
  Message = 'Message',
}

// ----------------------------------------------------------------------------
// Transaction Types
// ----------------------------------------------------------------------------
export type RawTransaction = {
  id: string;
  type: TransactionType;
  bytecodeRoot?: string;
  bytecodeWitnessIndex?: number;
  blobId?: string;
  inputAssetIds?: string[];
  inputContract?: RawInputContract;
  inputContracts?: string[];
  inputs: RawInput[];
  outputContract?: RawContractOutput;
  outputs: RawOutput[];
  isCreate: boolean;
  isMint: boolean;
  isScript: boolean;
  isUpgrade: boolean;
  isUpload: boolean;
  maturity?: number;
  mintAmount?: number;
  mintAssetId?: string;
  mintGasPrice?: number;
  policies?: {
    maxFee: number;
    witnessLimit: number;
    maturity: number;
    maxSize: number;
  };
  proofSet: string[];
  rawPayload: string;
  receiptsRoot?: string;
  salt?: string;
  script?: string;
  scriptData?: string;
  scriptGasLimit?: number;
  status: TransactionStatus;
  storageSlots: { key: string; value: string }[];
  subsectionIndex?: number;
  subsectionsNumber?: number;
  txPointer?: TxPointer;
  upgradePurpose?: number;
  witnesses: string[];
  receipts: RawReceipt[];
};

export type Transaction = FuelsTransaction;
export { TransactionType } from 'fuels';

export enum TransactionKind {
  Create = 'create',
  Mint = 'mint',
  Script = 'script',
  Upgrade = 'upgrade',
  Upload = 'upload',
  Blob = 'blob',
}

export enum TransactionStatus {
  Failed = 'failed',
  Submitted = 'submitted',
  SqueezedOut = 'squeezedOut',
  Success = 'success',
  None = 'none',
}
