/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - UtxosSubject
 */

import { UtxoParser } from '../../parsers';
import type { RawUtxo, Utxo } from '../../types';
import type { BlockHeight, HexData, TxId, UtxoType } from '../../types';
import { SubjectBase } from '../subject-base';

type UtxosFields = {
  utxoId: HexData;
  inputIndex: number;
  txId: TxId;
  txIndex: number;
  utxoType: UtxoType;
  blockHeight: BlockHeight;
};

export class UtxosSubject extends SubjectBase<UtxosFields, Utxo, RawUtxo> {
  metadata = {
    id: 'utxos',
    format:
      'utxos.{block_height}.{tx_id}.{tx_index}.{input_index}.{utxo_type}.{utxo_id}',
    parser: new UtxoParser(),
  };
}
