/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - UtxosSubject
 */

import { UtxoParser } from '../../parsers';
import type { RawUtxo, Utxo } from '../../types';
import type { MessageId, UtxoType } from '../../types';
import { SubjectBase } from '../subject-base';

type UtxosFields = {
  utxoType: UtxoType;
  hash: MessageId;
};

export class UtxosSubject extends SubjectBase<UtxosFields, Utxo, RawUtxo> {
  protected format = 'utxos.{utxo_type}.{hash}';
  entityParser() {
    return new UtxoParser();
  }
}
