/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - BlocksSubject
 */

import { BlockParser } from '../../parsers';
import type { Block, RawBlock } from '../../types';
import type { Address, BlockHeight } from '../../types';
import { SubjectBase } from '../subject-base';

type BlocksFields = {
  producer: Address;
  height: BlockHeight;
};

export class BlocksSubject extends SubjectBase<BlocksFields, Block, RawBlock> {
  protected format = 'blocks.{producer}.{height}';
  entityParser() {
    return new BlockParser();
  }
}
