name: Setup Bun
description: Install Bun tooling

inputs:
  bun-version:
    description: "Bun version to install"
    required: false
    default: "1.2.14"

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      name: Install Bun
      with:
        bun-version: ${{ inputs.bun-version }}
        cache: true

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
