/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - PredicatesSubject
 */

import { PredicateParser } from '../../parsers';
import type {
  Address,
  AssetId,
  BlockHeight,
  HexData,
  Predicate,
  RawPredicate,
  TxId,
} from '../../types';
import { SubjectBase } from '../subject-base';

type PredicatesFields = {
  blockHeight: BlockHeight;
  txId: TxId;
  txIndex: number;
  inputIndex: number;
  blobId: HexData;
  predicateAddress: Address;
  asset: AssetId;
};

export class PredicatesSubject extends SubjectBase<
  PredicatesFields,
  Predicate,
  RawPredicate
> {
  metadata = {
    id: 'predicates',
    format:
      'predicates.{block_height}.{tx_id}.{tx_index}.{input_index}.{blob_id}.{predicate_address}.{asset}',
    parser: new PredicateParser(),
  };
}
