/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - ReceiptsByIdSubject
 * - ReceiptsSubject
 * - ReceiptsCallSubject
 * - ReceiptsReturnSubject
 * - ReceiptsReturnDataSubject
 * - ReceiptsPanicSubject
 * - ReceiptsRevertSubject
 * - ReceiptsLogSubject
 * - ReceiptsLogDataSubject
 * - ReceiptsTransferSubject
 * - ReceiptsTransferOutSubject
 * - ReceiptsMintSubject
 * - ReceiptsBurnSubject
 * - ReceiptsScriptResultSubject
 * - ReceiptsMessageOutSubject
 */

import { ReceiptParser } from '../../parsers';
import type { RawReceipt, Receipt } from '../../types';
import type {
  Address,
  AssetId,
  Bytes32,
  ContractId,
  IdentifierKind,
} from '../../types';
import { SubjectBase } from '../subject-base';

type ReceiptsFields = {
  txId: Bytes32;
  index: number;
};

export class ReceiptsSubject extends SubjectBase<
  ReceiptsFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.>';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsByIdFields = {
  txId: Bytes32;
  index: number;
  idKind: IdentifierKind;
  idValue: Bytes32;
};

export class ReceiptsByIdSubject extends SubjectBase<
  ReceiptsByIdFields,
  Receipt,
  RawReceipt
> {
  protected format = 'by_id.receipts.{tx_id}.{index}.{id_kind}.{id_value}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsCallFields = {
  txId: Bytes32;
  index: number;
  from: ContractId;
  to: ContractId;
  assetId: AssetId;
};

export class ReceiptsCallSubject extends SubjectBase<
  ReceiptsCallFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.call.{from}.{to}.{asset_id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsReturnFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsReturnSubject extends SubjectBase<
  ReceiptsReturnFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.return.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsReturnDataFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsReturnDataSubject extends SubjectBase<
  ReceiptsReturnDataFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.return_data.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsPanicFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsPanicSubject extends SubjectBase<
  ReceiptsPanicFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.panic.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsRevertFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsRevertSubject extends SubjectBase<
  ReceiptsRevertFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.revert.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsLogFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsLogSubject extends SubjectBase<
  ReceiptsLogFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.log.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsLogDataFields = {
  txId: Bytes32;
  index: number;
  id: ContractId;
};

export class ReceiptsLogDataSubject extends SubjectBase<
  ReceiptsLogDataFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.log_data.{id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsTransferFields = {
  txId: Bytes32;
  index: number;
  from: ContractId;
  to: ContractId;
  assetId: AssetId;
};

export class ReceiptsTransferSubject extends SubjectBase<
  ReceiptsTransferFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.transfer.{from}.{to}.{asset_id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsTransferOutFields = {
  txId: Bytes32;
  index: number;
  from: ContractId;
  to: Address;
  assetId: AssetId;
};

export class ReceiptsTransferOutSubject extends SubjectBase<
  ReceiptsTransferOutFields,
  Receipt,
  RawReceipt
> {
  protected format =
    'receipts.{tx_id}.{index}.transfer_out.{from}.{to}.{asset_id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsMintFields = {
  txId: Bytes32;
  index: number;
  contractId: ContractId;
  subId: Bytes32;
};

export class ReceiptsMintSubject extends SubjectBase<
  ReceiptsMintFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.mint.{contract_id}.{sub_id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsBurnFields = {
  txId: Bytes32;
  index: number;
  contractId: ContractId;
  subId: Bytes32;
};

export class ReceiptsBurnSubject extends SubjectBase<
  ReceiptsBurnFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.burn.{contract_id}.{sub_id}';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsScriptResultFields = {
  txId: Bytes32;
  index: number;
};

export class ReceiptsScriptResultSubject extends SubjectBase<
  ReceiptsScriptResultFields,
  Receipt,
  RawReceipt
> {
  protected format = 'receipts.{tx_id}.{index}.script_result';
  entityParser() {
    return new ReceiptParser();
  }
}

type ReceiptsMessageOutFields = {
  txId: Bytes32;
  index: number;
  sender: Address;
  recipient: Address;
};

export class ReceiptsMessageOutSubject extends SubjectBase<
  ReceiptsMessageOutFields,
  Receipt,
  RawReceipt
> {
  protected format =
    'receipts.{tx_id}.{index}.message_out.{sender}.{recipient}';
  entityParser() {
    return new ReceiptParser();
  }
}
