/**
 * This file is auto-generated by scripts/generate-subjects.ts
 * Do not edit this file manually
 *
 * Generated Subjects:
 * - ReceiptsLogDataSubject
 * - ReceiptsPanicSubject
 * - ReceiptsMessageOutSubject
 * - ReceiptsBurnSubject
 * - ReceiptsMintSubject
 * - ReceiptsCallSubject
 * - ReceiptsReturnSubject
 * - ReceiptsRevertSubject
 * - ReceiptsReturnDataSubject
 * - ReceiptsTransferSubject
 * - ReceiptsTransferOutSubject
 * - ReceiptsScriptResultSubject
 * - ReceiptsLogSubject
 */

import { ReceiptParser } from '../../parsers';
import type { RawReceipt, Receipt } from '../../types';
import type {
  Address,
  AssetId,
  BlockHeight,
  Bytes32,
  ContractId,
  TxId,
} from '../../types';
import { SubjectBase } from '../subject-base';

type ReceiptsLogDataFields = {
  txIndex: number;
  txId: TxId;
  contract: ContractId;
  receiptIndex: number;
  blockHeight: BlockHeight;
};

export class ReceiptsLogDataSubject extends SubjectBase<
  ReceiptsLogDataFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_log_data',
    format:
      'receipts.log_data.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsPanicFields = {
  receiptIndex: number;
  txIndex: number;
  txId: TxId;
  contract: ContractId;
  blockHeight: BlockHeight;
};

export class ReceiptsPanicSubject extends SubjectBase<
  ReceiptsPanicFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_panic',
    format:
      'receipts.panic.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsMessageOutFields = {
  blockHeight: BlockHeight;
  txIndex: number;
  sender: Address;
  txId: TxId;
  receiptIndex: number;
  recipient: Address;
};

export class ReceiptsMessageOutSubject extends SubjectBase<
  ReceiptsMessageOutFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_message_out',
    format:
      'receipts.message_out.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{sender}.{recipient}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsBurnFields = {
  txId: TxId;
  receiptIndex: number;
  contract: ContractId;
  subId: Bytes32;
  blockHeight: BlockHeight;
  txIndex: number;
};

export class ReceiptsBurnSubject extends SubjectBase<
  ReceiptsBurnFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_burn',
    format:
      'receipts.burn.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}.{sub_id}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsMintFields = {
  blockHeight: BlockHeight;
  txId: TxId;
  subId: Bytes32;
  receiptIndex: number;
  contract: ContractId;
  txIndex: number;
};

export class ReceiptsMintSubject extends SubjectBase<
  ReceiptsMintFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_mint',
    format:
      'receipts.mint.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}.{sub_id}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsCallFields = {
  txId: TxId;
  from: ContractId;
  blockHeight: BlockHeight;
  txIndex: number;
  receiptIndex: number;
  to: ContractId;
  asset: AssetId;
};

export class ReceiptsCallSubject extends SubjectBase<
  ReceiptsCallFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_call',
    format:
      'receipts.call.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{from}.{to}.{asset}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsReturnFields = {
  txId: TxId;
  blockHeight: BlockHeight;
  txIndex: number;
  receiptIndex: number;
  contract: ContractId;
};

export class ReceiptsReturnSubject extends SubjectBase<
  ReceiptsReturnFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_return',
    format:
      'receipts.return.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsRevertFields = {
  contract: ContractId;
  txIndex: number;
  blockHeight: BlockHeight;
  txId: TxId;
  receiptIndex: number;
};

export class ReceiptsRevertSubject extends SubjectBase<
  ReceiptsRevertFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_revert',
    format:
      'receipts.revert.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsReturnDataFields = {
  contract: ContractId;
  txId: TxId;
  txIndex: number;
  blockHeight: BlockHeight;
  receiptIndex: number;
};

export class ReceiptsReturnDataSubject extends SubjectBase<
  ReceiptsReturnDataFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_return_data',
    format:
      'receipts.return_data.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsTransferFields = {
  txId: TxId;
  from: ContractId;
  txIndex: number;
  to: ContractId;
  asset: AssetId;
  blockHeight: BlockHeight;
  receiptIndex: number;
};

export class ReceiptsTransferSubject extends SubjectBase<
  ReceiptsTransferFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_transfer',
    format:
      'receipts.transfer.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{from}.{to}.{asset}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsTransferOutFields = {
  toAddress: Address;
  asset: AssetId;
  txIndex: number;
  from: ContractId;
  receiptIndex: number;
  blockHeight: BlockHeight;
  txId: TxId;
};

export class ReceiptsTransferOutSubject extends SubjectBase<
  ReceiptsTransferOutFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_transfer_out',
    format:
      'receipts.transfer_out.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{from}.{to_address}.{asset}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsScriptResultFields = {
  txId: TxId;
  blockHeight: BlockHeight;
  txIndex: number;
  receiptIndex: number;
};

export class ReceiptsScriptResultSubject extends SubjectBase<
  ReceiptsScriptResultFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_script_result',
    format:
      'receipts.script_result.{block_height}.{tx_id}.{tx_index}.{receipt_index}',
    parser: new ReceiptParser(),
  };
}

type ReceiptsLogFields = {
  blockHeight: BlockHeight;
  txId: TxId;
  txIndex: number;
  receiptIndex: number;
  contract: ContractId;
};

export class ReceiptsLogSubject extends SubjectBase<
  ReceiptsLogFields,
  Receipt,
  RawReceipt
> {
  metadata = {
    id: 'receipts_log',
    format:
      'receipts.log.{block_height}.{tx_id}.{tx_index}.{receipt_index}.{contract}',
    parser: new ReceiptParser(),
  };
}
