name: Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORC_VERSION: 0.63.3
  CORE_VERSION: 0.35.0
  NODE_VERSION: 20.11.0
  PNPM_VERSION: 9.5.0

jobs:
  tests-vitest:
    name: Vitest Tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - uses: FuelLabs/github-actions/setups/docker@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          name: my-toolchain
          components: forc@${{ env.FORC_VERSION }}, fuel-core@${{ env.CORE_VERSION }}

      # Unit tests running with Vitest
      - name: Find PR number
        uses: jwalton/gh-find-current-pr@v1
        if: ${{ github.event_name == 'pull_request' }}
        id: findPr

      - name: Run Vitest
        run: |
          pnpm test:ci
