name: Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Build packages
        run: bun run build:libs

      - name: Run unit tests
        run: bun run test

      - name: Install Playwright Browsers
        run: bun x playwright install --with-deps chromium

      - name: Run E2E tests
        run: bun run test:e2e
