name: "PR Checks"

on:
  pull_request:
    types: [opened, synchronize, edited, closed, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 20.11.0
  PNPM_VERSION: 9.5.0

jobs:
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # check-packages-changed:
  #   name: Assign project changed
  #   runs-on: ubuntu-latest
  #   outputs:
  #     changed: ${{ steps.packages-changed.outputs.any_changed }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Check external packages changes
  #       id: packages-changed
  #       uses: tj-actions/changed-files@v22.2
  #       with:
  #         files: |
  #           **/packages/fuel-streams/**
  #
  # validate-changeset:
  #   name: Validate PR Changeset
  #   needs: check-packages-changed
  #   # if: ${{ github.head_ref != 'changeset-release/main' && needs.check-packages-changed.outputs.changed == 'true' }}
  #   if: false
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #
  #     - name: Setup Node
  #       uses: FuelLabs/github-actions/setups/node@master
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         pnpm-version: ${{ env.PNPM_VERSION }}
  #
  #     - name: Validate Changeset
  #       run: pnpm changeset status --since=origin/${{ github.base_ref }}

  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - name: Build packages
        run: pnpm build:libs

      - name: Run lint & ts:check
        run: |
          pnpm lint:ci
          pnpm ts:check
