name: "Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  create-pr:
    name: Push changes to Changeset PR
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      contents: write
      pull-requests: write
    if: "!startsWith(github.event.head_commit.message, 'ci(changesets): versioning packages')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Changeset PR
        uses: changesets/action@v1
        with:
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    environment: npm-deploy
    if: "startsWith(github.event.head_commit.message, 'ci(changesets): versioning packages')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Remove package manager and engines from package.json
        run: |
          find . -name 'package.json' -exec node -e '
            const fs = require("fs");
            const file = process.argv[1];
            const pkg = JSON.parse(fs.readFileSync(file, "utf8"));
            delete pkg.packageManager;
            delete pkg.engines;
            fs.writeFileSync(file, JSON.stringify(pkg, null, 2));
          ' {} \;

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN_STREAMS }}

      - name: Bump and Collect Version
        run: |
          pnpm changeset version
          echo "BUILD_VERSION=$(pnpm -s packages:version)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build packages
        run: pnpm build:libs

      - name: Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@v2.0.0
        with:
          publish: pnpm changeset publish --tag latest
          createGithubReleases: aggregate
          version: pnpm changeset version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
