name: "Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  check-commit:
    name: Decide if releases or create PR
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      contents: read
      pull-requests: read
    outputs:
      is_changeset_pr: ${{ steps.check-commit.outputs.is_changeset_pr }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check-commit
        name: Check if this commit is a regular merge or a changeset PR merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          FIRST_LINE=$(echo "$COMMIT_MSG" | head -n1)
          if [[ "$FIRST_LINE" == "ci(changesets): versioning packages"* ]]; then
            PR_NUMBER=$(echo "$FIRST_LINE" | grep -o '#[0-9]\+' | head -n1 | tr -d '#')
            if [ -n "$PR_NUMBER" ]; then
              PR_TITLE=$(gh pr view "$PR_NUMBER" --json title -q .title)
              if [[ "$PR_TITLE" == "ci(changesets): versioning packages" ]]; then
                echo "is_changeset_pr=true" >> "$GITHUB_OUTPUT"
                exit 0
              fi
            fi
          fi
          echo "is_changeset_pr=false" >> "$GITHUB_OUTPUT"

  create-pr:
    name: Push changes to Changeset PR
    needs: check-commit
    if: needs.check-commit.outputs.is_changeset_pr == 'false'
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Changeset PR
        uses: changesets/action@v1
        with:
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Release to NPM
    needs: check-commit
    if: needs.check-commit.outputs.is_changeset_pr == 'true'
    runs-on: ubuntu-latest
    environment: npm-deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN_STREAMS }}

      - name: Bump and Collect Version
        run: |
          bun run changeset version
          echo "BUILD_VERSION=$(bun run --silent packages:version)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build packages
        run: bun run build:libs

      - name: Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@v2.0.0
        with:
          publish: bun run packages:publish
          createGithubReleases: aggregate
          version: bun run changeset version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
