name: "Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_VERSION: ""

jobs:
  release-changesets:
    environment: npm-deploy
    name: Release main or rc
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          # workaround to ensure force pushes to changeset branch use GITHUB_TOKEN owner's account
          # see https://github.com/changesets/action/issues/70
          persist-credentials: false

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN_STREAMS }}

      - name: Bump and Collect Version
        run: |
          bun run changeset version
          echo "BUILD_VERSION=$(bun run --silent packages:version)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup git user (for changelog step)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build Lib
        run: bun run build:libs

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: FuelLabs/changesets-action@main
        with:
          publish: bun run changeset publish --tag latest
          version: bun run changeset version
          commit: "ci(changesets): versioning packages"
          title: "ci(changesets): versioning packages"
          createGithubReleases: aggregate
          githubReleaseName: v${{ env.BUILD_VERSION }}
          githubTagName: v${{ env.BUILD_VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_STREAMS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
