name: "Unpublish old versions"

on:
  workflow_dispatch:
    inputs:
      delete_packages:
        type: boolean
        description: Delete the specified versions from npm
        default: false
      version:
        type: string
        description: Version(s) to delete (comma-separated for multiple versions e.g. "0.1.0,0.2.0")
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clean-npm-versions:
    name: Unpublish npm versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FuelLabs/github-actions/setups/node@master
        with:
          node-version: 20.11.0
          pnpm-version: 9.5.0
      - uses: FuelLabs/github-actions/setups/npm@master
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
      - run: pnpm install
      - run: pnpm tsx ./scripts/unpublish.ts
        env:
          DELETE_PACKAGES: ${{ github.event.inputs.delete_packages}}
          VERSION_TO_DELETE: ${{ github.event.inputs.version }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
